administration/urls.py
import datetime
import debug_toolbar


from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path, reverse_lazy
from django.views.i18n import JavaScriptCatalog
from django.views.decorators.http import last_modified
from django.contrib.auth.models import Group
from django.contrib.auth import views as auth_views

from administration.views import HomePageView, LoginPageView, RegisterView, \
    EditProfileView

last_modified_date = datetime.datetime.now()

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('login/', LoginPageView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('edit-profile/<int:pk>', EditProfileView.as_view(), name='edit-profile'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='administration/password_reset_confirm.html',
             success_url=reverse_lazy('password_reset_complete')), name='password_reset_confirm'),
    path('reset/', auth_views.PasswordResetView.as_view(
        template_name='administration/password_reset.html',
        email_template_name='administration/password_reset_email.html',
        subject_template_name='administration/password_reset_subject.txt',
        success_url=reverse_lazy('password_reset_done')), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='administration/password_reset_done.html'),
        name='password_reset_done'),
    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(
                template_name='administration/password_reset_complete.html'),
        name='password_reset_complete'),
    path('admin/', admin.site.urls, name='admin'),
    path('', include(('appointments.urls', 'appointments'), namespace='appointments')),
]

urlpatterns += [
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', last_modified(lambda req, **kw: last_modified_date)(
        JavaScriptCatalog.as_view()), name='javascript-catalog'),
]

admin.site.site_header = "Administrare Pacienti"
admin.site.site_title = "Administrare Pacienti"
admin.site.index_title = "Bine ai venit!"

admin.site.unregister(Group)

admin.site.site_url = '/'

appointments/urls.py
import datetime

from django.urls import path

from appointments.views import CreateAppointmentView, EditAppointmentView, \
    MedicDailyAppointmentView, MedicEditAppointmentView, PatientsView, DeleteAppointmentView, \
    PatientsHistoryAppointsView, PatientsAppointsViewOnly

last_modified_date = datetime.datetime.now()

urlpatterns = [
    path('appointment/create/', CreateAppointmentView.as_view(), name='create-appointment'),
    path('appointment/edit/<int:pk>', EditAppointmentView.as_view(), name='edit-appointment'),
    path('appointment/delete/<int:pk>', DeleteAppointmentView.as_view(), name='delete-appointment'),
    path('medic-appointment/edit/<int:pk>', MedicEditAppointmentView.as_view(), name='medic-edit-appointment'),
    path('patient-appointments/<int:pk>', PatientsHistoryAppointsView.as_view(), name='patient-appointments'),
    path('patient-appointment-view/<int:pk>', PatientsAppointsViewOnly.as_view(), name='patient-appointment-view'),
    path('medic-appointments/<slug:date>', MedicDailyAppointmentView.as_view(), name='medic-appointments'),
    path('patients/', PatientsView.as_view(), name='patients'),
]

appointments/forms.py
import datetime
import pytz

from bootstrap_datepicker_plus import DateTimePickerInput
from django import forms
from django.db.models import Q

from appointments.models import Appointments


class AppointmentsForm(forms.ModelForm):
    class Meta:
        model = Appointments
        fields = ('medic', 'scheduled_datetime', 'description', 'disease', 'symptoms')
        widgets = {
            'scheduled_datetime': DateTimePickerInput(),
        }

    def __init__(self, *args, **kwargs):
        super(AppointmentsForm, self).__init__(*args, **kwargs)
        self.fields['medic'].queryset = self.fields['medic'].queryset.exclude(Q(is_patient=True) | Q(is_superuser=True))

    def clean_scheduled_datetime(self):
        scheduled_datetime = self.cleaned_data.get('scheduled_datetime')
        scheduled_datetime_start = scheduled_datetime - datetime.timedelta(minutes=30)
        medic = self.cleaned_data.get('medic')
        now = datetime.datetime.now(pytz.timezone('Europe/Bucharest'))
        start_program = scheduled_datetime.replace(hour=10, minute=0, second=0, microsecond=0)
        end_program = scheduled_datetime.replace(hour=16, minute=0, second=0, microsecond=0)
        if scheduled_datetime <= now:
            raise forms.ValidationError("Nu se poate selecta o data din trecut")
        if scheduled_datetime < start_program or scheduled_datetime > end_program:
            raise forms.ValidationError("Intervalul orar pentru programari este 10:00-16:00")
        if scheduled_datetime.isoweekday() not in range(1, 5):
            raise forms.ValidationError("Programarile se pot realiza de Luni pana Vineri")
        if self.instance.pk:
            appointment = Appointments.objects \
                .filter(medic=medic, scheduled_datetime__range=[scheduled_datetime_start, scheduled_datetime]) \
                .exclude(pk=self.instance.pk).exists()
        else:
            appointment = Appointments.objects \
                .filter(medic=medic, scheduled_datetime__range=[scheduled_datetime_start, scheduled_datetime]) \
                .exists()
        if appointment:
            raise forms.ValidationError("Data si ora programarii nu sunt disponibile")
        return scheduled_datetime


class MedicAppointmentsForm(forms.ModelForm):
    class Meta:
        model = Appointments
        fields = ('treatment',)

appointments/views.py
import datetime

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic import ListView
from django.core.mail import send_mail
from django.conf import settings
from django.shortcuts import get_object_or_404, redirect
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.http import Http404, HttpResponseRedirect
from django.db import connection

from administration.mixins import LogInMixin
from appointments.models import Appointments
from appointments.forms import AppointmentsForm, MedicAppointmentsForm
from appointments.query import AppointmentsQuery
from users.models import User
from users.query import UserQuery


class CreateAppointmentView(LogInMixin, CreateView):
    template_name = 'appointments/create-appointment.html'
    form_class = AppointmentsForm
    success_url = '/'

    def form_valid(self, form):
        scheduled = form.cleaned_data['scheduled_datetime']
        with connection.cursor() as cursor:
            cursor.execute(
                    AppointmentsQuery.CHECK_APPOINTMENTS_SCHEDULE.format(
                        medic_id=form.cleaned_data['medic'].pk,
                        patient_id=self.request.user.pk,
                        day=scheduled.day
                    )
                )
            data = cursor.fetchone()
        if data and data[0] == 1:
            form.add_error("scheduled_datetime", "Exista deja o programare creata in aceasta zi")
            return super().form_invalid(form)
        obj = form.save(commit=False)
        obj.patient = self.request.user
        mail_subject = "Consultatie creata"
        html_message_patient = render_to_string('appointments/appointment_create_email.html',
                                        {'appointment': obj})
        html_message_medic = render_to_string('appointments/appointment_create_medic_email.html',
                                                {'appointment': obj})
        plain_message_patient = strip_tags(html_message_patient)
        plain_message_medic = strip_tags(html_message_medic)
        send_mail(
            mail_subject, plain_message_patient, settings.EMAIL_HOST_USER,
            [obj.patient.email], html_message=html_message_patient)
        send_mail(
            mail_subject, plain_message_medic, settings.EMAIL_HOST_USER,
            [obj.medic.email], html_message=html_message_medic)
        obj.save()
        return super().form_valid(form)


class EditAppointmentView(LogInMixin, UpdateView):
    template_name = 'appointments/create-appointment.html'
    form_class = AppointmentsForm
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        # check if there is some video onsite
        appointment = self.get_object()
        if appointment.status != Appointments.IN_PROGRESS:
            return redirect('appointments:patient-appointment-view', pk=appointment.pk)
        return super(EditAppointmentView, self).dispatch(request, *args, **kwargs)

    def get_object(self, *args, **kwargs):
        appointments = Appointments.objects.raw(AppointmentsQuery.GET_APPOINTMENT.format(pk=self.kwargs['pk']))
        if len(appointments) == 0:
            raise Http404('No matches the given query.')
        return appointments[0]

    def form_valid(self, form):
        old_object = self.get_object()
        obj = form.save(commit=False)
        with connection.cursor() as cursor:
            cursor.execute(
                    AppointmentsQuery.UPDATE_APPOINTMENT.format(
                        medic_id=obj.medic.pk,
                        patient_id=self.request.user.pk,
                        scheduled=obj.scheduled_datetime.strftime("%Y-%m-%d %H:%M:%S"),
                        description=obj.description,
                        disease_id=obj.disease_id,
                        status=obj.status,
                        treatment=obj.treatment,
                        pk=obj.pk
                    )
                )
            old_symptoms = old_object.symptoms.values_list('pk', flat=True)
            new_symptoms = [symptom.pk for symptom in form.cleaned_data['symptoms']]
            symptoms_to_delete = list(set(old_symptoms) - set(new_symptoms))
            symptoms_to_add = list(set(new_symptoms) - set(old_symptoms))
            if symptoms_to_delete:
                for pk in symptoms_to_delete:
                    cursor.execute(
                        AppointmentsQuery.DELETE_APPOINTMENTS_SYMPTOMS_BY_SYMPTOMS.format(
                            appointment_pk=obj.pk,
                            symptom_pk=pk
                        )
                    )
            if symptoms_to_add:
                for pk in symptoms_to_add:
                    cursor.execute(
                        AppointmentsQuery.INSERT_SYMPTOMS.format(
                            appointment_pk=obj.pk,
                            symptom_pk=pk
                        )
                    )
        return HttpResponseRedirect(self.get_success_url())


class DeleteAppointmentView(LogInMixin, DeleteView):
    model = Appointments
    success_url = '/'

    def get_object(self, *args, **kwargs):
        appointments = Appointments.objects.raw(AppointmentsQuery.GET_APPOINTMENT.format(pk=self.kwargs['pk']))
        if len(appointments) == 0:
            raise Http404('No matches the given query.')
        return appointments[0]

    def delete(self, request, *args, **kwargs):
        appointment = self.get_object()
        mail_subject = "Consultatie anulata"
        html_message = render_to_string('appointments/appointment_delete_email.html',
                                        {'appointment': appointment})
        plain_message = strip_tags(html_message)
        send_mail(
            mail_subject, plain_message, settings.EMAIL_HOST_USER,
            [appointment.patient.email, appointment.medic.email], html_message=html_message)
        with connection.cursor() as cursor:
            cursor.execute(
                AppointmentsQuery.DELETE_APPOINTMENTS_SYMPTOMS.format(pk=appointment.pk)
            )
            cursor.execute(
                AppointmentsQuery.DELETE_APPOINTMENTS.format(pk=appointment.pk)
            )
        return HttpResponseRedirect(self.success_url)


class MedicDailyAppointmentView(LogInMixin, ListView):
    template_name = 'appointments/medic-daily-appointment.html'

    def get_queryset(self):
        date = self.kwargs['date']
        date = datetime.datetime.strptime(date, '%Y-%m-%d')
        return Appointments.objects.filter(scheduled_datetime__day=date.day) \
            .order_by('scheduled_datetime')


class MedicEditAppointmentView(LogInMixin, UpdateView):
    template_name = 'appointments/medic-edit-appointment.html'
    form_class = MedicAppointmentsForm
    success_url = '/'

    def get_object(self, *args, **kwargs):
        return get_object_or_404(Appointments, pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super(MedicEditAppointmentView, self).get_context_data(**kwargs)
        patient = self.get_object().patient
        context['appointments'] = patient.appointmentspatient \
            .filter(status=Appointments.RESOLVED).exclude(pk=self.kwargs['pk'])
        context['appointment'] = self.get_object()
        return context

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.status = Appointments.RESOLVED
        mail_subject = "Rezultat consultatie"
        html_message = render_to_string('appointments/appointment_email.html',
                                        {'appointment': obj})
        plain_message = strip_tags(html_message)
        send_mail(
            mail_subject, plain_message, settings.EMAIL_HOST_USER,
            [obj.patient.email], html_message=html_message)
        obj.save()
        return super().form_valid(form)


class PatientsView(LogInMixin, ListView):
    template_name = 'appointments/view-patients.html'

    def get_queryset(self):
        return Appointments.objects.raw(AppointmentsQuery.GET_MEDIC_APPOINTMENTS.format(medic=self.request.user.pk))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PatientsView, self).get_context_data(**kwargs)
        patients = []
        for appointment in self.get_queryset():
            if appointment.patient not in patients:
                patients.append(appointment.patient.pk)
        search = self.request.GET.get('q')
        filters = {'pk': ','.join([str(p) for p in patients])}
        if search:
            filters['filters'] = f"AND cnp='{search}'"
        else:
            filters['filters'] = ""
        context['patients'] = User.objects.raw(AppointmentsQuery.GET_PATIENTS.format(**filters))
        return context


class PatientsHistoryAppointsView(LogInMixin, ListView):
    template_name = 'appointments/patient-appointments-history.html'

    def get_queryset(self):
        user = User.objects.raw(UserQuery.GET_USER.format(pk=self.kwargs['pk']))
        if len(user) == 0:
            raise Http404('No matches the given query.')
        return user[0]

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PatientsHistoryAppointsView, self).get_context_data(**kwargs)
        patient = self.get_queryset()
        context['appointments'] = Appointments.objects.raw(
            AppointmentsQuery.GET_PATIENT_APPOINTMENTS_WITH_STATUS.format(
                patient_id=patient.pk, status=Appointments.RESOLVED))
        return context


class PatientsAppointsViewOnly(LogInMixin, DetailView):
    template_name = 'appointments/patient-view-appointment.html'

    def get_object(self, *args, **kwargs):
        appointments = Appointments.objects.raw(AppointmentsQuery.GET_APPOINTMENT.format(pk=self.kwargs['pk']))
        if len(appointments) == 0:
            raise Http404('No matches the given query.')

templates/appointments/appointment_create_email.html
Buna ziua,<br>
consultatia din data de {{ appointment.scheduled_datetime|date:"d-m-Y H:i" }} la medicul {{ appointment.medic.first_name }} {{ appointment.medic.last_name }} a fost creata.
<br><br>
Va multumim!

templates/appointments/appointment_create_medic_email.html
Buna ziua,<br>
a fost creata o noua consultatie in data de {{ appointment.scheduled_datetime|date:"d-m-Y H:i" }} de catre pacientul {{ appointment.patient.first_name }} {{ appointment.patient.last_name }}
<br><br>
Va multumim!

templates/appointments/appointment_delete_email.html
Buna ziua,<br>
Consultatia din data de {{ appointment.scheduled_datetime|date:"d-m-Y H:i" }} a fost anulata.
<br><br>
Va multumim!

templates/appointments/appointment_email.html
Buna ziua,<br>
rezultatul consultatiei din data de {{ appointment.scheduled_datetime }} la medicul {{ appointment.medic.first_name }} {{ appointment.medic.last_name }} este:<br>
<br>
{{ appointment.treatment }}
<br><br>
Va multumim!

templates/appointments/appointments_confirm_delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{{ form.media }}

{% block menu_buttons %}
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">Acasa<span class="sr-only">(current)</span></a>
      </li>
    </ul>
{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
    <p>Doriti sa anulati programea din data "{{ object.scheduled_datetime|date:"d-m-Y H:i"  }}"?</p>
    <button type="submit" class="btn btn-primary btn-sm">Da</button>
</form>
{% endblock %}

templates/appointments/create-appointment.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{{ form.media }}

{% block menu_buttons %}
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">Acasa</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'appointments:create-appointment' %}">Adaugare consultatie<span class="sr-only">(current)</span></a>
      </li>
    </ul>
{% endblock %}

{% block content %}
    <form method="post" id="entry">
        {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
        {% csrf_token %}
        {{form.media}}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary btn-sm">Creare consultatie</button>
    </form>
{% endblock %}

templates/appointments/medic-daily-appointment.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block menu_buttons %}
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">Acasa<span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'appointments:patients' %}">Vizualizare pacienti</a>
        </li>
    </ul>
{% endblock %}

{% block content %}
    <table class="table">
        <thead class="thead-inverse">
            <tr>
                <th>Pacient</th>
                <th>Descriere</th>
                <th>Boala</th>
                <th>Simptome</th>
                <th>Data programarii</th>
                <th>Anulare programare</th>
            </tr>
        </thead>
        <tbody>
            {% for data in object_list %}
                <tr>
                    <td class="align-middle">
                        <a href="{% url 'appointments:medic-edit-appointment' data.pk %}">
                            {% if data.patient.first_name %}
                                {{data.patient.first_name}}
                            {% else %}
                                -
                            {% endif %}
                            {% if data.patient.last_name %}
                                {{data.patient.last_name}}
                            {% else %}
                                -
                            {% endif %}
                        </a>
                    </td>
                    <td class="align-middle">
                        <a href="{% url 'appointments:medic-edit-appointment' data.pk %}">{{data.description}}</a>
                    </td>
                    <td class="align-middle">
                        <a href="{% url 'appointments:medic-edit-appointment' data.pk %}">{{data.disease}}</a>
                    </td>
                    <td class="align-middle">
                        {% for symptom in data.symptoms.all %}
                            <a href="{% url 'appointments:medic-edit-appointment' data.pk %}">{{symptom.name}}</a> <br>
                        {% endfor %}
                    </td>
                    <td class="align-middle">
                        <a href="{% url 'appointments:medic-edit-appointment' data.pk %}">{{data.scheduled_datetime|date:"d-m-Y H:i"}}</a>
                    </td>
                    <td class="align-middle">
                        {% if data.can_be_cancelled == False %}
                            <a href="{% url 'appointments:delete-appointment' data.pk %}">Anuleaza programare</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/appointments/medic-edit-appointment.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{{ form.media }}

{% block menu_buttons %}
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Acasa</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'appointments:patients' %}">Vizualizare pacienti</a>
        </li>
    </ul>
{% endblock %}

{% block content %}
    <h3> {{appointments.first.patient.first_name}} {{appointments.first.patient.last_name}}</h3><br>
    <table class="table">
        <thead class="thead-inverse">
            <tr>
                <th>Descriere</th>
                <th>Boala</th>
                <th>Simptome</th>
                <th>Data programarii</th>
                <th>Tratament</th>
            </tr>
        </thead>
        <tbody>
            {% for data in appointments %}
                <tr>
                    <td class="align-middle">
                        {{data.description}}
                    </td>
                    <td class="align-middle">
                        {{data.disease}}
                    </td>
                    <td class="align-middle">
                        {% for symptom in data.symptoms.all %}
                            {{symptom.name}}<br>
                        {% endfor %}
                    </td>
                    <td class="align-middle">
                        {{data.scheduled_datetime|date:"d-m-Y H:i" }}
                    </td>
                    <td class="align-middle">
                        {{data.treatment}}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% for symptom in appointment.symptoms.all %}
        {{symptom.name}}<br>
    {% endfor %}
    Descriere: {{appointment.description}}<br><br>
    <form method="post" id="entry">
        {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
        {% if appointment.status != 1%}
            Tratament: {{appointment.treatment}}
        {% else %}
            {% csrf_token %}
            {{form.media}}
            {% bootstrap_form form %}
                <button type="submit" class="btn btn-primary btn-sm">Incheie tratament</button>
        {% endif %}
    </form>
{% endblock %}

templates/appointments/patient-appointments-history.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{{ form.media }}

{% block menu_buttons %}
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Acasa</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'appointments:patients' %}">Vizualizare pacienti</a>
        </li>
    </ul>
{% endblock %}

{% block content %}
    <h3>Patient: {{appointments.first.patient.first_name}} {{appointments.first.patient.last_name}}</h3><br>
    <table class="table">
        <thead class="thead-inverse">
            <tr>
                <th>Descriere</th>
                <th>Boala</th>
                <th>Simptome</th>
                <th>Data programarii</th>
                <th>Tratament</th>
            </tr>
        </thead>
        <tbody>
            {% for data in appointments %}
                <tr>
                    <td class="align-middle">
                        {{data.description}}
                    </td>
                    <td class="align-middle">
                        {{data.disease}}
                    </td>
                    <td class="align-middle">
                        {% for symptom in data.symptoms.all %}
                            {{symptom.name}}<br>
                        {% endfor %}
                    </td>
                    <td class="align-middle">
                        {{data.scheduled_datetime|date:"d-m-Y H:i" }}
                    </td>
                    <td class="align-middle">
                        {{data.treatment}}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/appointments/patient-view-appointment.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{{ form.media }}

{% block menu_buttons %}
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Acasa</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'appointments:patients' %}">Vizualizare pacienti</a>
        </li>
    </ul>
{% endblock %}

{% block content %}
    <h4>Medic: {{ appointment.medic }}</h4>
    <h4>Boala: {{ appointment.disease }}</h4>
    <h4>Simptome:
        {% for symptom in appointment.symptoms.all %}
            {{symptom.name}}<br>

        {% endfor %}
    </h4>
    <h4>Data programarii: {{appointment.scheduled_datetime|date:"d-m-Y H:i" }}</h4>
    <h4>Tratament: {{appointment.treatment }}</h4>
{% endblock %}

templates/appointments/view-patients.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block menu_buttons %}
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Acasa</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'appointments:patients' %}">Vizualizare pacienti</a>
        </li>
    </ul>
{% endblock %}

{% block content %}
    <br>
    <form method="get" action="">
        <div align="right">
        <input type="text" name="q" placeholder="Cauta pacient" value="{{ request.GET.q }}"/>
        <input type="submit" class="btn btn-primary btn-sm" value="Cautare"/>
        </div>
    </form>
    <br>
    <table class="table">
        <thead class="thead-inverse">
            <tr>
                <th>Nume</th>
                <th>Email</th>
                <th>Varsta</th>
                <th>Numar telefon</th>
                <th>CNP</th>
            </tr>
        </thead>
        <tbody>
            {% for patient in patients %}
                <tr>
                    <td class="align-middle">
                        <a href="{% url 'appointments:patient-appointments' patient.pk %}">
                            {% if patient.first_name %}
                                {{patient.first_name}}
                            {% else %}
                                -
                            {% endif %}
                            {% if patient.last_name %}
                                {{patient.last_name}}
                            {% else %}
                                -
                            {% endif %}
                        </a>
                    </td>
                    <td class="align-middle">
                        <a href="{% url 'appointments:patient-appointments' patient.pk %}">
                            {{patient.email}}
                        </a>
                    </td>
                    <td class="align-middle">
                        <a href="{% url 'appointments:patient-appointments' patient.pk %}">
                            {% if patient.dob %}
                                {{patient.dob}}
                            {% else %}
                                -
                            {% endif %}
                        </a>
                    </td>
                    <td class="align-middle">
                        <a href="{% url 'appointments:patient-appointments' patient.pk %}">
                            {% if patient.phone %}
                                {{patient.phone}}
                            {% else %}
                                -
                            {% endif %}
                        </a>
                    </td>
                    <td class="align-middle">
                        <a href="{% url 'appointments:patient-appointments' patient.pk %}">
                            {{patient.cnp}}
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}