administration/urls.py
import datetime
import debug_toolbar


from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path, reverse_lazy
from django.views.i18n import JavaScriptCatalog
from django.views.decorators.http import last_modified
from django.contrib.auth.models import Group
from django.contrib.auth import views as auth_views

from administration.views import HomePageView, LoginPageView, RegisterView, \
    EditProfileView

last_modified_date = datetime.datetime.now()

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('login/', LoginPageView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('edit-profile/<int:pk>', EditProfileView.as_view(), name='edit-profile'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='administration/password_reset_confirm.html',
             success_url=reverse_lazy('password_reset_complete')), name='password_reset_confirm'),
    path('reset/', auth_views.PasswordResetView.as_view(
        template_name='administration/password_reset.html',
        email_template_name='administration/password_reset_email.html',
        subject_template_name='administration/password_reset_subject.txt',
        success_url=reverse_lazy('password_reset_done')), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='administration/password_reset_done.html'),
        name='password_reset_done'),
    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(
                template_name='administration/password_reset_complete.html'),
        name='password_reset_complete'),
    path('admin/', admin.site.urls, name='admin'),
    path('', include(('appointments.urls', 'appointments'), namespace='appointments')),
]

urlpatterns += [
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', last_modified(lambda req, **kw: last_modified_date)(
        JavaScriptCatalog.as_view()), name='javascript-catalog'),
]

admin.site.site_header = "Administrare Pacienti"
admin.site.site_title = "Administrare Pacienti"
admin.site.index_title = "Bine ai venit!"

admin.site.unregister(Group)

admin.site.site_url = '/'

appointments/urls.py
import datetime

from django.urls import path

from appointments.views import CreateAppointmentView, EditAppointmentView, \
    MedicDailyAppointmentView, MedicEditAppointmentView, PatientsView, DeleteAppointmentView, \
    PatientsHistoryAppointsView, PatientsAppointsViewOnly

last_modified_date = datetime.datetime.now()

urlpatterns = [
    path('appointment/create/', CreateAppointmentView.as_view(), name='create-appointment'),
    path('appointment/edit/<int:pk>', EditAppointmentView.as_view(), name='edit-appointment'),
    path('appointment/delete/<int:pk>', DeleteAppointmentView.as_view(), name='delete-appointment'),
    path('medic-appointment/edit/<int:pk>', MedicEditAppointmentView.as_view(), name='medic-edit-appointment'),
    path('patient-appointments/<int:pk>', PatientsHistoryAppointsView.as_view(), name='patient-appointments'),
    path('patient-appointment-view/<int:pk>', PatientsAppointsViewOnly.as_view(), name='patient-appointment-view'),
    path('medic-appointments/<slug:date>', MedicDailyAppointmentView.as_view(), name='medic-appointments'),
    path('patients/', PatientsView.as_view(), name='patients'),
]

administration/forms.py
from django import forms

from users.models import User, alphanumeric, cnp_length


class RegisterForm(forms.ModelForm):
    first_name = forms.CharField(max_length=40)
    last_name = forms.CharField(max_length=40)
    cnp = forms.CharField(max_length=40, validators=[alphanumeric, cnp_length])
    password = forms.CharField(max_length=40, widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'cnp', 'password')


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone', 'dob')

administration/views.py
from django.views.generic import ListView, CreateView, UpdateView
from django.contrib.auth.views import LoginView
from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.http import Http404
from django.db import connection

from administration.mixins import LogInMixin
from administration.forms import RegisterForm, EditProfileForm
from appointments.models import Appointments
from appointments.query import AppointmentsQuery
from users.models import User
from users.query import UserQuery


class HomePageView(LogInMixin, ListView):
    def get_template_names(self):
        if self.request.user.is_patient:
            return 'administration/home-patient.html'
        return 'administration/home-medic.html'

    def get_queryset(self):
        if self.request.user.is_patient:
            return Appointments.objects.raw(
                AppointmentsQuery.GET_PATIENT_APPOINTMENTS.format(patient_id=self.request.user.pk))
        return Appointments.objects.raw(
            AppointmentsQuery.GET_MEDIC_APPOINTMENTS.format(medic=self.request.user.pk))

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        with connection.cursor() as cursor:
            if self.request.user.is_patient:
                cursor.execute(
                    AppointmentsQuery.GET_PATIENT_APPOINTMENTS_NUMBER.format(patient_id=self.request.user.pk)
                )
            else:
                cursor.execute(
                    AppointmentsQuery.GET_MEDIC_APPOINTMENTS_NUMBER.format(medic=self.request.user.pk)
                )
            nr_appointments = cursor.fetchone()
            nr_appointments = nr_appointments[0]
        context['nr_appointments'] = nr_appointments
        return context


class LoginPageView(LoginView):
    template_name = 'administration/login.html'
    redirect_authenticated_user = 'home'


class RegisterView(CreateView):
    template_name = 'administration/register.html'
    form_class = RegisterForm
    success_url = '/'

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.is_patient = True
        obj.set_password(form.cleaned_data['password'])
        obj.is_active = True
        mail_subject = "Date cont Administare pacienti"
        context_data = {
            'user': obj,
        }
        html_message = render_to_string(
            'administration/register_email.html', context_data)

        plain_message = strip_tags(html_message)
        send_mail(
            mail_subject, plain_message, settings.EMAIL_HOST_USER,
            [obj.email], html_message=html_message)
        obj.save()
        return super().form_valid(form)


class EditProfileView(LogInMixin, UpdateView):
    template_name = 'administration/edit-profile.html'
    form_class = EditProfileForm
    success_url = '/'

    def get_object(self, *args, **kwargs):
        user = User.objects.raw(UserQuery.GET_USER.format(pk=self.kwargs['pk']))
        if len(user) == 0:
            raise Http404('No matches the given query.')
        return user[0]

templates/administration/edit-profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{{ form.media }}

{% block menu_buttons %}
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Acasa</a>
        </li>
    </ul>
{% endblock %}

{% block content %}
    <form method="post" id="entry">
        {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
        {% csrf_token %}
        {{form.media}}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary btn-sm">Submit</button>
    </form>
{% endblock %}

templates/administration/home-medic.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block stylesheet %}
<style>
.public {
  height: 25px;
  width: 150px;
  background-color: #2eb82e;
}
.private {
  height: 25px;
  width: 150px;
  background-color: #3A87AD;
}
</style>
{% endblock %}

{% block menu_buttons %}
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#">Acasa<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'appointments:patients' %}">Vizualizare pacienti</a>
      </li>
    </ul>
{% endblock %}

{% block content %}
    <h3>Consultatii: {{nr_appointments}}</h3>
    <div class="container">
       <div id="calendar"></div>
        <div class="card" >
        <div class="card-body">
        </div>
      </div>
    </div>

{% endblock %}

{% block javascript %}
    <script src="{% static 'moment.min.js.css' %}"></script>
    <script src="{% static 'jquery.min.js' %}"></script>
    <script src="{% static 'jquery-ui.custom.min.js' %}"></script>
    <script src="{% static 'fullcalendar.min.js' %}"></script>
    <script>
        $(document).ready(function() {
            $('#calendar').fullCalendar({
                editable: true,
                eventLimit: true, // allow "more" link when too many events
                header:{
                    left: 'prev, next today',
                    center: 'title',
                    right: 'month, agendaWeek, agendaDay'
                },
                events: [
                    {% for appointment in object_list %}
                    {
                        title: "{{ appointment.patient.first_name }} {{ appointment.patient.last_name }}",
                        start: '{{ appointment.scheduled_datetime|date:"Y-m-d" }}'
                    },
                    {% endfor %}
                ],
                dayClick: function(date, jsEvent, view) {
                    var getUrl = window.location;
                    var baseUrl = getUrl .protocol + "//" + getUrl.host + "/" + getUrl.pathname.split('/')[1];
                    window.location.href = baseUrl + 'medic-appointments/' + date.format();
                },
            });
        });
    </script>
{% endblock %}

templates/administration/home-patient.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block menu_buttons %}
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Acasa<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'appointments:create-appointment' %}">Adaugare consultatie</a>
      </li>
    </ul>
{% endblock %}

{% block content %}
    <small>Consultatii: {{nr_appointments}}</small>
    <table class="table">
        <thead class="thead-inverse">
            <tr>
                <th>Medic</th>
                <th>Descriere</th>
                <th>Boala</th>
                <th>Simptome</th>
                <th>Data programarii</th>
                <th>Anulare programare</th>
            </tr>
        </thead>
        <tbody>
            {% for data in object_list %}
                <tr>
                    <td class="align-middle">
                        <a href="{% url 'appointments:edit-appointment' data.pk %}">
                            {% if data.medic.first_name %}
                                {{data.medic.first_name}}
                            {% else %}
                                -
                            {% endif %}
                            {% if data.medic.last_name %}
                                {{data.medic.last_name}}
                            {% else %}
                                -
                            {% endif %}
                        </a>
                    </td>
                    <td class="align-middle">
                        <a href="{% url 'appointments:edit-appointment' data.pk %}">{{data.description}}</a>
                    </td>
                    <td class="align-middle">
                        <a href="{% url 'appointments:edit-appointment' data.pk %}">{{data.disease}}</a>
                    </td>
                    <td class="align-middle">
                        {% for symptom in data.symptoms.all %}
                            <a href="{% url 'appointments:edit-appointment' data.pk %}">{{symptom.name}}</a> <br>
                        {% endfor %}
                    </td>
                    <td class="align-middle">
                        <a href="{% url 'appointments:edit-appointment' data.pk %}">{{data.scheduled_datetime|date:"d-m-Y H:i" }}</a>
                    </td>
                    <td class="align-middle">
                        {% if data.can_be_cancelled == False %}
                            <a href="{% url 'appointments:delete-appointment' data.pk %}">Anuleaza programare</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/administration/login.html
{% extends 'base_accounts.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card">
            <div class="card-body">
                {% if user.is_authenticated %}
                <h3 class="card-title">You are logged in</h3>
                    <a href="{% url 'logout' %}">Log Out</a>
                    {% else %}
                    <form method="post">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <button type="submit" class="btn btn-primary btn-block">Autentificare</button>
                    </form>
            </div>
            <div class="card-footer text-muted text-center">
                <a href="{% url 'password_reset' %}" class="text-muted">Recuperare parola</a>
            </div>
            <div class="card-footer text-muted text-center">
                <a href="{% url 'register' %}" class="text-muted">Creare cont pacient</a>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/administration/password_reset.html
{% extends 'base_accounts.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6 col-sm-8">
            <div class="card">
                <div class="card-body">
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <button type="submit"
                                class="btn btn-primary btn-block">Resetare parola
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/administration/password_reset_complete.html
{% extends 'base_accounts.html' %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Parola a fost schimbata!</h3>
                <div class="alert alert-success" role="alert">
                    Parola a fost schimbata cu succes!
                </div>
                <a href="{% url 'login' %}" class="btn btn-secondary btn-block">Log In</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/administration/password_reset_confirm.html
{% extends 'base_accounts.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-4 col-md-4 col-sm-10">
        <div class="card">
            <div class="card-body">
                {% if validlink %}
                    <h3 class="card-title">Schimba parola pentru contul: {{ form.user.email }}</h3>
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <button type="submit"
                                class="btn btn-primary btn-block">Creare cont
                        </button>
                    </form>
                {% else %}
                <h3 class="card-title">Schimba parola</h3>
                <div class="alert alert-danger" role="alert">
                    Link-ul este invalid
                </div>
                <a href="{% url 'password_reset' %}" class="btn btn-secondary btn-block">Genereaza un nou link</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/administration/password_reset_done.html
{% extends 'base_accounts.html' %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Schimba parola</h3>
                <p>Link-ul pentru resetarea parolei a fost trimis pe adresa dumneavoastra de email.</p>
                <a href="{% url 'login' %}" class="btn btn-secondary btn-block">Log In</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/administration/password_reset_email.html
Buna,

Ai solicitat schimbarea parolei pentru adresa de email {{ email }}. Acceseaza urmatorul link:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

templates/administration/register.html
{% extends 'base_accounts.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6 col-sm-8">
            <div class="card">
                <div class="card-body">
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <button type="submit"
                                class="btn btn-primary btn-block">Creare cont
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/administration/register_email.html
Buna ziua,<br>
Datele contului dumneavoastra sunt:
<br>
Email: {{ user.email }}<br>
CNP: {{ user.cnp }}<br>
Prenume: {{ user.first_name }}<br>
Nume: {{ user.last_name }}<br>
<br><br>
Va multumim!